language: node_js
node_js:
  - "iojs"
  - "6"
  - "5"
  - "4"
services:
  - postgresql
before_script:
  - psql -c 'create database rocketleague;' -U postgres
  - npm install -g supervisor
  - npm start &
